"""initial schema (all 19 tables, spec §5.3–5.21)

Revision ID: 0001
Revises: 
Create Date: generated by scripts/gen_migrations.py
"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    op.execute("""CREATE TABLE audit_events (
	tenant_id VARCHAR(36) COMMENT '租户ID（索引）', 
	trace_id VARCHAR(64) COMMENT '链路 trace_id（索引）', 
	request_id VARCHAR(64) COMMENT '请求 request_id（索引）', 
	stage VARCHAR(64) COMMENT '阶段（索引）', 
	actor VARCHAR(64) NOT NULL COMMENT '行为主体：agent/node', 
	model VARCHAR(128) COMMENT '模型名', 
	tool VARCHAR(128) COMMENT '工具名', 
	provider VARCHAR(128) COMMENT 'Provider 名', 
	input_json JSON COMMENT '输入（JSON）', 
	output_json JSON COMMENT '输出（JSON）', 
	latency_ms BIGINT COMMENT '耗时（毫秒）', 
	status VARCHAR(32) NOT NULL COMMENT '状态：success/error/timeout', 
	error_code VARCHAR(64) COMMENT '错误码', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_audit_events PRIMARY KEY (id)
)COMMENT='审计事件表'""")
    op.execute("""CREATE INDEX ix_audit_events_request_id ON audit_events (request_id)""")
    op.execute("""CREATE INDEX ix_audit_events_stage ON audit_events (stage)""")
    op.execute("""CREATE INDEX ix_audit_events_tenant_id ON audit_events (tenant_id)""")
    op.execute("""CREATE INDEX ix_audit_events_trace_id ON audit_events (trace_id)""")
    op.execute("""CREATE TABLE evaluation_datasets (
	name VARCHAR(255) NOT NULL COMMENT '数据集名称', 
	version VARCHAR(64) NOT NULL COMMENT '数据集版本', 
	task_type VARCHAR(64) NOT NULL COMMENT '任务类型', 
	case_count INTEGER NOT NULL COMMENT '用例数量', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_evaluation_datasets PRIMARY KEY (id)
)COMMENT='评估数据集表'""")
    op.execute("""CREATE TABLE provider_health (
	provider_name VARCHAR(64) NOT NULL COMMENT 'Provider 名称（索引）', 
	capability VARCHAR(64) NOT NULL COMMENT '能力点（索引）', 
	status VARCHAR(32) NOT NULL COMMENT '状态：healthy/degraded/down', 
	success_rate NUMERIC(8, 6) NOT NULL COMMENT '成功率', 
	last_success_at DATETIME(3) COMMENT '最近成功时间（UTC）', 
	last_failure_at DATETIME(3) COMMENT '最近失败时间（UTC）', 
	failure_count INTEGER NOT NULL COMMENT '累计失败次数', 
	updated_at DATETIME(3) NOT NULL COMMENT '更新时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_provider_health PRIMARY KEY (id)
)COMMENT='Provider 健康度表'""")
    op.execute("""CREATE INDEX ix_provider_health_capability ON provider_health (capability)""")
    op.execute("""CREATE INDEX ix_provider_health_provider_name ON provider_health (provider_name)""")
    op.execute("""CREATE TABLE tenants (
	name VARCHAR(120) NOT NULL COMMENT '租户名（唯一）', 
	status VARCHAR(32) NOT NULL COMMENT '状态：active/disabled', 
	id VARCHAR(36) NOT NULL, 
	created_at DATETIME(3) NOT NULL, 
	updated_at DATETIME(3) NOT NULL, 
	CONSTRAINT pk_tenants PRIMARY KEY (id), 
	CONSTRAINT uq_tenants_name UNIQUE (name)
)COMMENT='租户表'""")
    op.execute("""CREATE TABLE users (
	email VARCHAR(255) NOT NULL COMMENT '邮箱（唯一）', 
	display_name VARCHAR(120) NOT NULL COMMENT '显示名', 
	password_hash VARCHAR(255) COMMENT '密码哈希（可为空，如仅 OAuth 登录）', 
	status VARCHAR(32) NOT NULL COMMENT '状态：active/disabled', 
	id VARCHAR(36) NOT NULL, 
	created_at DATETIME(3) NOT NULL, 
	updated_at DATETIME(3) NOT NULL, 
	CONSTRAINT pk_users PRIMARY KEY (id), 
	CONSTRAINT uq_users_email UNIQUE (email)
)COMMENT='用户表'""")
    op.execute("""CREATE TABLE documents (
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID（外键，索引）', 
	title VARCHAR(500) NOT NULL COMMENT '文档标题', 
	source_type VARCHAR(64) NOT NULL COMMENT '来源类型：upload/web/financial', 
	source_uri TEXT COMMENT '来源 URI', 
	sha256 VARCHAR(64) NOT NULL COMMENT '内容 SHA256（唯一）', 
	company VARCHAR(255) COMMENT '关联公司', 
	ticker VARCHAR(64) COMMENT '证券代码', 
	market VARCHAR(32) COMMENT '市场', 
	document_type VARCHAR(64) COMMENT '文档类型', 
	report_period VARCHAR(32) COMMENT '报告期', 
	published_at DATETIME(3) COMMENT '发布时间（UTC）', 
	authority_tier SMALLINT NOT NULL COMMENT '权威层级（数值，越高越权威）', 
	status VARCHAR(32) NOT NULL COMMENT '状态：ingested/failed/archived', 
	id VARCHAR(36) NOT NULL, 
	created_at DATETIME(3) NOT NULL, 
	updated_at DATETIME(3) NOT NULL, 
	CONSTRAINT pk_documents PRIMARY KEY (id), 
	CONSTRAINT fk_documents_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	CONSTRAINT uq_documents_sha256 UNIQUE (sha256)
)COMMENT='文档表'""")
    op.execute("""CREATE INDEX ix_documents_company ON documents (company)""")
    op.execute("""CREATE INDEX ix_documents_document_type ON documents (document_type)""")
    op.execute("""CREATE INDEX ix_documents_market ON documents (market)""")
    op.execute("""CREATE INDEX ix_documents_report_period ON documents (report_period)""")
    op.execute("""CREATE INDEX ix_documents_tenant_id ON documents (tenant_id)""")
    op.execute("""CREATE INDEX ix_documents_ticker ON documents (ticker)""")
    op.execute("""CREATE TABLE evaluation_cases (
	dataset_id VARCHAR(36) NOT NULL COMMENT '所属数据集ID（外键，索引）', 
	query TEXT NOT NULL COMMENT '查询文本', 
	expected_json JSON NOT NULL COMMENT '期望输出（JSON）', 
	tags_json JSON NOT NULL COMMENT '标签（JSON）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_evaluation_cases PRIMARY KEY (id), 
	CONSTRAINT fk_evaluation_cases_dataset_id_evaluation_datasets FOREIGN KEY(dataset_id) REFERENCES evaluation_datasets (id)
)COMMENT='评估用例表'""")
    op.execute("""CREATE INDEX ix_evaluation_cases_dataset_id ON evaluation_cases (dataset_id)""")
    op.execute("""CREATE TABLE evaluation_runs (
	dataset_id VARCHAR(36) NOT NULL COMMENT '数据集ID（外键）', 
	git_commit VARCHAR(64) NOT NULL COMMENT '代码版本 git commit hash', 
	model_name VARCHAR(128) NOT NULL COMMENT '被评模型名', 
	embedding_model VARCHAR(128) NOT NULL COMMENT 'Embedding 模型', 
	reranker_model VARCHAR(128) NOT NULL COMMENT 'Reranker 模型', 
	config_json JSON NOT NULL COMMENT '运行配置（JSON）', 
	metrics_json JSON NOT NULL COMMENT '评估指标（JSON）', 
	started_at DATETIME(3) NOT NULL COMMENT '开始时间（UTC）', 
	finished_at DATETIME(3) COMMENT '结束时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_evaluation_runs PRIMARY KEY (id), 
	CONSTRAINT fk_evaluation_runs_dataset_id_evaluation_datasets FOREIGN KEY(dataset_id) REFERENCES evaluation_datasets (id)
)COMMENT='评估运行表'""")
    op.execute("""CREATE TABLE provider_configs (
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID（外键，索引）', 
	provider_name VARCHAR(64) NOT NULL COMMENT 'Provider 名称', 
	enabled BOOL NOT NULL COMMENT '是否启用（TINYINT(1)）', 
	priority INTEGER NOT NULL COMMENT '优先级（数值，越小越优先）', 
	config_json JSON NOT NULL COMMENT '自定义配置（JSON）', 
	id VARCHAR(36) NOT NULL, 
	created_at DATETIME(3) NOT NULL, 
	updated_at DATETIME(3) NOT NULL, 
	CONSTRAINT pk_provider_configs PRIMARY KEY (id), 
	CONSTRAINT uq_provider_configs_tenant_provider UNIQUE (tenant_id, provider_name), 
	CONSTRAINT fk_provider_configs_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id)
)COMMENT='Provider 配置表'""")
    op.execute("""CREATE INDEX ix_provider_configs_tenant_id ON provider_configs (tenant_id)""")
    op.execute("""CREATE TABLE sessions (
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID（外键，索引）', 
	user_id VARCHAR(36) NOT NULL COMMENT '用户ID（外键，索引）', 
	title VARCHAR(255) NOT NULL COMMENT '会话标题', 
	summary TEXT COMMENT '会话摘要', 
	status VARCHAR(32) NOT NULL COMMENT '状态：active/completed/archived', 
	id VARCHAR(36) NOT NULL, 
	created_at DATETIME(3) NOT NULL, 
	updated_at DATETIME(3) NOT NULL, 
	CONSTRAINT pk_sessions PRIMARY KEY (id), 
	CONSTRAINT fk_sessions_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	CONSTRAINT fk_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
)COMMENT='会话表'""")
    op.execute("""CREATE INDEX ix_sessions_tenant_id ON sessions (tenant_id)""")
    op.execute("""CREATE INDEX ix_sessions_user_id ON sessions (user_id)""")
    op.execute("""CREATE TABLE user_tenants (
	user_id VARCHAR(36) NOT NULL COMMENT '用户ID', 
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID', 
	`role` VARCHAR(32) NOT NULL COMMENT '在该租户内的角色', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	CONSTRAINT pk_user_tenants PRIMARY KEY (user_id, tenant_id), 
	CONSTRAINT uq_user_tenants_user_tenant UNIQUE (user_id, tenant_id), 
	CONSTRAINT fk_user_tenants_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), 
	CONSTRAINT fk_user_tenants_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id)
)COMMENT='用户与租户的关联表'""")
    op.execute("""CREATE TABLE document_chunks (
	document_id VARCHAR(36) NOT NULL COMMENT '所属文档ID（外键，索引）', 
	chunk_index INTEGER NOT NULL COMMENT '片段序号', 
	page INTEGER COMMENT '页码', 
	section VARCHAR(500) COMMENT '章节标题', 
	text_hash VARCHAR(64) NOT NULL COMMENT '片段文本 SHA256', 
	text_length INTEGER NOT NULL COMMENT '片段文本长度', 
	milvus_pk VARCHAR(128) COMMENT 'Milvus 主键（预留）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_document_chunks PRIMARY KEY (id), 
	CONSTRAINT uq_document_chunks_doc_idx UNIQUE (document_id, chunk_index), 
	CONSTRAINT fk_document_chunks_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id), 
	CONSTRAINT uq_document_chunks_milvus_pk UNIQUE (milvus_pk)
)COMMENT='文档片段表'""")
    op.execute("""CREATE INDEX ix_document_chunks_document_id ON document_chunks (document_id)""")
    op.execute("""CREATE TABLE messages (
	session_id VARCHAR(36) NOT NULL COMMENT '会话ID（外键，索引）', 
	`role` VARCHAR(32) NOT NULL COMMENT '角色：user/assistant/system', 
	content TEXT(4294967295) NOT NULL COMMENT '消息内容（LONGTEXT）', 
	structured_answer_json JSON COMMENT '结构化回答（JSON，预留）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_messages PRIMARY KEY (id), 
	CONSTRAINT fk_messages_session_id_sessions FOREIGN KEY(session_id) REFERENCES sessions (id)
)COMMENT='会话消息表'""")
    op.execute("""CREATE INDEX ix_messages_session_id ON messages (session_id)""")
    op.execute("""CREATE TABLE research_tasks (
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID（外键，索引）', 
	session_id VARCHAR(36) NOT NULL COMMENT '会话ID（外键，索引）', 
	type VARCHAR(64) NOT NULL COMMENT '任务类型：research_qa/financial_health/due_diligence/report/api/upload', 
	query TEXT NOT NULL COMMENT '用户查询文本', 
	status VARCHAR(32) NOT NULL COMMENT '任务状态：pending/running/succeeded/failed/cancelled', 
	trace_id VARCHAR(64) NOT NULL COMMENT '链路 trace_id（唯一）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	started_at DATETIME(3) COMMENT '开始时间（UTC）', 
	finished_at DATETIME(3) COMMENT '结束时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_research_tasks PRIMARY KEY (id), 
	CONSTRAINT fk_research_tasks_tenant_id_tenants FOREIGN KEY(tenant_id) REFERENCES tenants (id), 
	CONSTRAINT fk_research_tasks_session_id_sessions FOREIGN KEY(session_id) REFERENCES sessions (id), 
	CONSTRAINT uq_research_tasks_trace_id UNIQUE (trace_id)
)COMMENT='研究任务表'""")
    op.execute("""CREATE INDEX ix_research_tasks_session_id ON research_tasks (session_id)""")
    op.execute("""CREATE INDEX ix_research_tasks_tenant_id ON research_tasks (tenant_id)""")
    op.execute("""CREATE TABLE evidence (
	tenant_id VARCHAR(36) NOT NULL COMMENT '租户ID（索引）', 
	document_id VARCHAR(36) NOT NULL COMMENT '来源文档ID（外键）', 
	chunk_id VARCHAR(36) NOT NULL COMMENT '来源片段ID（外键）', 
	provider VARCHAR(64) COMMENT '数据来源 Provider', 
	relevance_score NUMERIC(8, 6) NOT NULL COMMENT '相关度得分', 
	authority_score NUMERIC(8, 6) NOT NULL COMMENT '权威度得分', 
	retrieved_at DATETIME(3) NOT NULL COMMENT '检索时间（UTC）', 
	evidence_json JSON NOT NULL COMMENT '证据详情（JSON）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_evidence PRIMARY KEY (id), 
	CONSTRAINT fk_evidence_document_id_documents FOREIGN KEY(document_id) REFERENCES documents (id), 
	CONSTRAINT fk_evidence_chunk_id_document_chunks FOREIGN KEY(chunk_id) REFERENCES document_chunks (id)
)COMMENT='证据表'""")
    op.execute("""CREATE INDEX ix_evidence_tenant_idx ON evidence (tenant_id)""")
    op.execute("""CREATE TABLE research_runs (
	research_task_id VARCHAR(36) NOT NULL COMMENT '研究任务ID（外键，索引）', 
	workflow_name VARCHAR(64) NOT NULL COMMENT '工作流名称', 
	graph_version VARCHAR(32) NOT NULL COMMENT 'LangGraph 图版本', 
	model_name VARCHAR(128) COMMENT '主模型名称', 
	model_version VARCHAR(128) COMMENT '主模型版本', 
	status VARCHAR(32) NOT NULL COMMENT '运行状态：running/succeeded/failed', 
	confidence NUMERIC(8, 6) COMMENT '整体置信度', 
	result_json JSON COMMENT '运行结果（JSON）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	finished_at DATETIME(3) COMMENT '结束时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_research_runs PRIMARY KEY (id), 
	CONSTRAINT fk_research_runs_research_task_id_research_tasks FOREIGN KEY(research_task_id) REFERENCES research_tasks (id)
)COMMENT='研究运行记录表'""")
    op.execute("""CREATE INDEX ix_research_runs_research_task_id ON research_runs (research_task_id)""")
    op.execute("""CREATE TABLE calculations (
	research_run_id VARCHAR(36) NOT NULL COMMENT '研究运行ID（外键，索引）', 
	formula TEXT NOT NULL COMMENT '计算表达式（确定性代码生成）', 
	inputs_json JSON NOT NULL COMMENT '计算输入（JSON）', 
	output_value NUMERIC(30, 8) NOT NULL COMMENT '计算输出数值', 
	output_unit VARCHAR(32) COMMENT '输出单位', 
	output_currency VARCHAR(16) COMMENT '输出币种', 
	period VARCHAR(32) COMMENT '所属期间', 
	source_evidence_ids_json JSON NOT NULL COMMENT '依据证据ID列表（JSON）', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_calculations PRIMARY KEY (id), 
	CONSTRAINT fk_calculations_research_run_id_research_runs FOREIGN KEY(research_run_id) REFERENCES research_runs (id)
)COMMENT='计算记录表'""")
    op.execute("""CREATE INDEX ix_calculations_research_run_id ON calculations (research_run_id)""")
    op.execute("""CREATE TABLE claims (
	research_run_id VARCHAR(36) NOT NULL COMMENT '研究运行ID（外键，索引）', 
	claim_type VARCHAR(32) NOT NULL COMMENT '论断类型', 
	text TEXT NOT NULL COMMENT '论断文本', 
	confidence NUMERIC(8, 6) NOT NULL COMMENT '置信度', 
	verified BOOL NOT NULL COMMENT '是否通过校验（TINYINT(1)）', 
	verification_reason TEXT COMMENT '校验结论说明', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	id VARCHAR(36) NOT NULL, 
	CONSTRAINT pk_claims PRIMARY KEY (id), 
	CONSTRAINT fk_claims_research_run_id_research_runs FOREIGN KEY(research_run_id) REFERENCES research_runs (id)
)COMMENT='论断表'""")
    op.execute("""CREATE INDEX ix_claims_research_run_id ON claims (research_run_id)""")
    op.execute("""CREATE TABLE claim_evidence (
	claim_id VARCHAR(36) NOT NULL COMMENT '论断ID', 
	evidence_id VARCHAR(36) NOT NULL COMMENT '证据ID', 
	created_at DATETIME(3) NOT NULL COMMENT '创建时间（UTC）', 
	CONSTRAINT pk_claim_evidence PRIMARY KEY (claim_id, evidence_id), 
	CONSTRAINT uq_claim_evidence_pair UNIQUE (claim_id, evidence_id), 
	CONSTRAINT fk_claim_evidence_claim_id_claims FOREIGN KEY(claim_id) REFERENCES claims (id), 
	CONSTRAINT fk_claim_evidence_evidence_id_evidence FOREIGN KEY(evidence_id) REFERENCES evidence (id)
)COMMENT='论断与证据的关联表'""")
    op.execute("SET FOREIGN_KEY_CHECKS=1")

def downgrade() -> None:
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    op.execute("""DROP TABLE claim_evidence""")
    op.execute("""DROP TABLE claims""")
    op.execute("""DROP TABLE calculations""")
    op.execute("""DROP TABLE research_runs""")
    op.execute("""DROP TABLE evidence""")
    op.execute("""DROP TABLE research_tasks""")
    op.execute("""DROP TABLE messages""")
    op.execute("""DROP TABLE document_chunks""")
    op.execute("""DROP TABLE user_tenants""")
    op.execute("""DROP TABLE sessions""")
    op.execute("""DROP TABLE provider_configs""")
    op.execute("""DROP TABLE evaluation_runs""")
    op.execute("""DROP TABLE evaluation_cases""")
    op.execute("""DROP TABLE documents""")
    op.execute("""DROP TABLE users""")
    op.execute("""DROP TABLE tenants""")
    op.execute("""DROP TABLE provider_health""")
    op.execute("""DROP TABLE evaluation_datasets""")
    op.execute("""DROP TABLE audit_events""")
    op.execute("SET FOREIGN_KEY_CHECKS=1")
