"""离线生成 Alembic 初始迁移（T102）。

原理：直接用 MySQL 方言编译 Base.metadata 中每张表的 CREATE TABLE DDL（SQLAlchemy 的
MySQL 方言会内联 PRIMARY KEY / UNIQUE / FOREIGN KEY / INDEX / 列与表的中文注释），
写入 `migrations/versions/<rev>_initial_schema.py`。由于 DDL 就是由 model（= 规格 §5）
编译而来，因此迁移与模型/规格逐列绝对一致，且无需依赖运行中的数据库即可生成。

用法（项目根运行）：
    python scripts/gen_migrations.py

生成后应用：
    python scripts/init_db.py
"""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from sqlalchemy import MetaData  # noqa: E402
from sqlalchemy.dialects import mysql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable, DropTable  # noqa: E402

from finsage.persistence import models as _  # noqa: E402,F401  # 注册全部表
from finsage.persistence.base import Base  # noqa: E402

REVISION = "0001"
VERSION_DIR = PROJECT_ROOT / "migrations" / "versions"
HEADER = (
    '"""initial schema (all 19 tables, spec §5.3–5.21)\n'
    "\n"
    "Revision ID: 0001\n"
    "Revises: \n"
    "Create Date: generated by scripts/gen_migrations.py\n"
    '"""\n'
    "from __future__ import annotations\n\n"
    "from alembic import op\n\n"
    "# revision identifiers, used by Alembic.\n"
    f"revision = {REVISION!r}\n"
    "down_revision = None\n"
    "branch_labels = None\n"
    "depends_on = None\n\n"
)


def _compile_ddl(statement: object, dialect: mysql.dialect) -> str:
    return str(statement.compile(dialect=dialect, compile_kwargs={"literal_binds": True})).strip()


def generate(revision: str = REVISION) -> Path:
    """生成初始迁移文件，返回其路径。"""
    VERSION_DIR.mkdir(parents=True, exist_ok=True)
    dialect = mysql.dialect()

    metadata: MetaData = Base.metadata
    tables = list(metadata.sorted_tables)  # 依赖顺序：被引用表在前，保证外键创建顺序

    body: list[str] = [HEADER]
    body.append('def upgrade() -> None:\n    op.execute("SET FOREIGN_KEY_CHECKS=0")\n')
    for table in tables:
        create_sql = _compile_ddl(CreateTable(table), dialect)
        body.append(f"    op.execute(\"\"\"{create_sql}\"\"\")\n")
        # 普通索引（index=True / 显式 Index）不会被 CreateTable 内联渲染，需单独 CREATE INDEX。
        for index in sorted(table.indexes, key=lambda ix: ix.name or ""):
            index_ddl = _compile_ddl(CreateIndex(index), dialect)
            body.append(f"    op.execute(\"\"\"{index_ddl}\"\"\")\n")
    body.append("    op.execute(\"SET FOREIGN_KEY_CHECKS=1\")\n\n")

    body.append("def downgrade() -> None:\n    op.execute(\"SET FOREIGN_KEY_CHECKS=0\")\n")
    for table in reversed(tables):
        drop = _compile_ddl(DropTable(table), dialect)
        body.append(f"    op.execute(\"\"\"{drop}\"\"\")\n")
    body.append("    op.execute(\"SET FOREIGN_KEY_CHECKS=1\")\n")

    out = VERSION_DIR / f"{revision}_initial_schema.py"
    out.write_text("".join(body), encoding="utf-8")
    return out


if __name__ == "__main__":
    path = generate()
    print(f"已生成迁移文件: {path}")
    print("应用：python scripts/init_db.py")
    print("离线预览 SQL：alembic upgrade head --sql")